name: Contract Service CI

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'contract-service/**'

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service-name: contract-service
    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}