name: Payment Service CI

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'payment-service/**'

permissions:
  pull-requests: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service-name: payment-service
    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}